### ISSUE TITLE
Can't start the program

### ISSUE THREAD

**Issue by matthewalampe** [voidbydefault/EasyApplyBot#12]
I tried the new code but I get the following error - have you seen this before?

Traceback (most recent call last):
  File "C:\Users\mal\Downloads\EasyApplyBot-master (3)\EasyApplyBot-master\main.py", line 114, in <module>
    browser = init_browser()
  File "C:\Users\mal\Downloads\EasyApplyBot-master (3)\EasyApplyBot-master\main.py", line 20, in init_browser
    driver = webdriver.Chrome(service=service, options=browser_options)
TypeError: __init__() got an unexpected keyword argument 'service'

**Comment by matthewalampe** [comment]
This can be closed. The latest version of selenium corrected the issue
