### ISSUE TITLE
securityClearnace

### ISSUE THREAD

**Issue by matthewalampe** [voidbydefault/EasyApplyBot#14]
Every time I download the new code I get this error

I fix it by adding securityClearance to the config.yaml

I thought I would let you know so you could add it to code

Traceback (most recent call last):
  File "C:\Users\mal\Downloads\EasyApplyBot-master (4)\EasyApplyBot-master\main.py", line 130, in <module>
    parameters = validate_yaml()
  File "C:\Users\mal\Downloads\EasyApplyBot-master (4)\EasyApplyBot-master\main.py", line 103, in validate_yaml
    assert isinstance(checkboxes['securityClearance'], bool)
KeyError: 'securityClearance'

**Comment by voidbydefault** [comment]
It already exists in `config.yaml`, you just need to add an answer (and above error will pop-up if you don't set anything or set anything other than True/False):

![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/480c5925-ad73-4873-b98f-7d0dee8dda1e)

Not an issue. Closing.
