### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by EasyApplyBotUser** [voidbydefault/EasyApplyBot#25]
C:\Users\ideap\Demo\EasyApplyBot\venv\Scripts\python.exe C:\Users\ideap\Demo\EasyApplyBot\main.py 
Traceback (most recent call last):
  File "C:\Users\ideap\Demo\EasyApplyBot\main.py", line 132, in <module>
    parameters = validate_yaml()
  File "C:\Users\ideap\Demo\EasyApplyBot\main.py", line 35, in validate_yaml
    raise exc
 I followed the instructions in the August video and I'm not sure what went wrong. There are the problems I'm facing

```
 File "C:\Users\ideap\Demo\EasyApplyBot\main.py", line 33, in validate_yaml
    parameters = yaml.safe_load(stream)
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\ideap\Demo\EasyApplyBot\venv\lib\site-packages\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "config.yaml", line 130, column 2
expected <block end>, but found '<scalar>'
  in "config.yaml", line 131, column 3

Process finished with exit code 1
```

**Comment by voidbydefault** [comment]
>  in "config.yaml", line 130, column 2
>  in "config.yaml", line 131, column 3

Sounds like an issue with your `config.yaml`. You aren't setting it properly, go to lines 130-131 in your config and try to spot error.
