### ISSUE TITLE
Selenium WebDriver is unable to establish a connection with the browser's renderer process?

### ISSUE THREAD

**Issue by dmike23** [voidbydefault/EasyApplyBot#40]
Hi. Thanks for all your work on this. I am receiving a WebDriverException error. Not sure why my Chrome app or whatever WebDriver main.py is using (i gather it uses the latest version available based on my understanding of the code) is failing. 

I have confirmed I am using the latest version of chrome. 

I figured I don't need to disable any extensions in any of my chrome profiles because main.py creates a fresh temporary profile, right?

I am using Python 3.10 in PyCharms.

Any thoughts on solving this?

Thanks

`C:\Users\micha\.virtualenvs\easyaps\Scripts\python.exe C:\Users\micha\PycharmProjects\easyaps\main.py 
Traceback (most recent call last):
  File "C:\Users\micha\PycharmProjects\easyaps\main.py", line 137, in <module>
    browser = init_browser()
  File "C:\Users\micha\PycharmProjects\easyaps\main.py", line 24, in init_browser
    driver = webdriver.Chrome(service=service, options=browser_options)
  File "C:\Users\micha\.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\micha\.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\micha\.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\micha\.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\micha\.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\micha\.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: unable to connect to renderer
Stacktrace:
	GetHandleVerifier [0x004972A3+45731]
	(No symbol) [0x00422D51]
	(No symbol) [0x0031880D]
	(No symbol) [0x00340F2B]
	(No symbol) [0x0033D7E9]
	(No symbol) [0x0033A310]
	(No symbol) [0x0036EB26]
	(No symbol) [0x0036E6BC]
	(No symbol) [0x00367DD6]
	(No symbol) [0x003431F6]
	(No symbol) [0x0034439D]
	GetHandleVerifier [0x007A0716+3229462]
	GetHandleVerifier [0x007E84C8+3523784]
	GetHandleVerifier [0x007E214C+3498316]
	GetHandleVerifier [0x00521680+611968]
	(No symbol) [0x0042CCCC]
	(No symbol) [0x00428DF8]
	(No symbol) [0x00428F1D]
	(No symbol) [0x0041B2C7]
	BaseThreadInitThunk [0x7654FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x773C7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x773C7C3E+238]

Process finished with exit code 1`
![image](https://github.com/voidbydefault/EasyApplyBot/assets/17505146/6559e074-e64b-40e1-928e-4ea8d5a592bd)

**Comment by dmike23** [comment]
> Hi. Thanks for all your work on this. I am receiving a WebDriverException error. Not sure why my Chrome app or whatever WebDriver main.py is using (i gather it uses the latest version available based on my understanding of the code) is failing.
> 
> I have confirmed I am using the latest version of chrome.
> 
> I figured I don't need to disable any extensions in any of my chrome profiles because main.py creates a fresh temporary profile, right?
> 
> I am using Python 3.10 in PyCharms.
> 
> Any thoughts on solving this?
> 
> Thanks
> 
> `C:\Users\micha.virtualenvs\easyaps\Scripts\python.exe C:\Users\micha\PycharmProjects\easyaps\main.py Traceback (most recent call last): File "C:\Users\micha\PycharmProjects\easyaps\main.py", line 137, in browser = init_browser() File "C:\Users\micha\PycharmProjects\easyaps\main.py", line 24, in init_browser driver = webdriver.Chrome(service=service, options=browser_options) File "C:\Users\micha.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in **init** super().**init**( File "C:\Users\micha.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in **init** super().**init**( File "C:\Users\micha.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in **init** self.start_session(capabilities) File "C:\Users\micha.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session response = self.execute(Command.NEW_SESSION, caps)["value"] File "C:\Users\micha.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute self.error_handler.check_response(response) File "C:\Users\micha.virtualenvs\easyaps\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: disconnected: unable to connect to renderer Stacktrace: GetHandleVerifier [0x004972A3+45731] (No symbol) [0x00422D51] (No symbol) [0x0031880D] (No symbol) [0x00340F2B] (No symbol) [0x0033D7E9] (No symbol) [0x0033A310] (No symbol) [0x0036EB26] (No symbol) [0x0036E6BC] (No symbol) [0x00367DD6] (No symbol) [0x003431F6] (No symbol) [0x0034439D] GetHandleVerifier [0x007A0716+3229462] GetHandleVerifier [0x007E84C8+3523784] GetHandleVerifier [0x007E214C+3498316] GetHandleVerifier [0x00521680+611968] (No symbol) [0x0042CCCC] (No symbol) [0x00428DF8] (No symbol) [0x00428F1D] (No symbol) [0x0041B2C7] BaseThreadInitThunk [0x7654FCC9+25] RtlGetAppContainerNamedObjectPath [0x773C7C6E+286] RtlGetAppContainerNamedObjectPath [0x773C7C3E+238]
> 
> Process finished with exit code 1` ![image](https://private-user-images.githubusercontent.com/17505146/285681740-6559e074-e64b-40e1-928e-4ea8d5a592bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTUxNjEsIm5iZiI6MTcwMTE5NDg2MSwicGF0aCI6Ii8xNzUwNTE0Ni8yODU2ODE3NDAtNjU1OWUwNzQtZTY0Yi00MGUxLTkyOGUtNGVhOGQ1YTU5MmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE4MDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YjcxMWU3NzExNWQ0OTUyN2Y5NDY1ZThiZjI3NjkzMzIyODliODU5NDNjZjU2NzY0YmVkNTUzZDU4NWU1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YNKAlEILFebUpdFlf93lp70DWKlySNqbfkfdkpvz_PQ)

This seemed to be a Pycharms issue. Restarting my IDE solved the error.
